export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORY_START: 'FETCH_CATEGORY_START',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',
}